### ISSUE TITLE
9月1日升级到WLK以后 插件不能用了

### ISSUE THREAD

**Issue by xinxininnanjing** [DengSir/tdAuction#4]
上架商品 每次都显示拍卖行内部错误 烦请大佬更新下 感谢 么么哒

**Comment by tytannial** [comment]
能用，国服特色10秒API调用CD，也就是说本来上架货物后会使用一次搜索价格接口，你必须10秒后再点击上架按钮。

**Comment by xinxininnanjing** [comment]
感谢大佬回复，这就去试试。

发自我的iPhone
